### ISSUE TITLE
Unusable Ram with Player count 600+

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#10773]
Hello,
today we had a huge Fight in the Chaos Waste, when i saw the Population Mod in /1 it was always at atleast 400+ ppl. At some point there where even over 600+ ppl in CW. Because of the amount of ppl playing and fighting we had some major lag. It was really as if you had pictures to look at instead of frames.
What happend was that i tryed to spawn a Ram, the spawning worked well, but when i mounted up and tryed to tow the Ram, the Ram was heavily Rubberbanding and lagging. Im also very sure the Ram had problems, and not me, because everyone else saw the Ram literally "flying" away too cause of the Rubberbanding. So me and some fellow RvR players tryed to spawn 3 times a Ram, everytime the same result on different players with different Ram types. The Ram started Rubberbanding, lagging and after about 1 min doing this it was just "flying" backwards from the player that towed it to some random place, after that it couldnt be towed anymore and destroyed itself which meant we had to wait again to place a new ram.
Some time later some players left CW and the overall lagging stopped, then we could use Rams again.

Hope i could help, thanks in advance to all Devs and GMs that read this.

Solutar.

**Comment by MaxHayman** [comment]
@sioding I'm guessing this was fixed when we fixed lag.

**Comment by sioding** [comment]
True - Close

**Comment by XmatXergon** [comment]
seems like issue is back, it was laggy a bit in TM but RAM was teleporting like crazy yesterday :(

**Comment by dalen** [comment]
this also happened in Reikland yesterday with high population.

**Comment by MaxHayman** [comment]
Going to close this as I did some fixes and we haven't had ram issues in a while.
