### ISSUE TITLE
Watchtower of Aethwyn; Public Quest

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11423]
Two bugs exist within this PQ,

1) When a Zealot class enters the PQ area, the PQ information does not show up, e.g. what the objective is a/o how much time remains for the PQ.

2) The beginning objective is to collect 50 glass shards. You can go from 0/50 to 50/50 in just a minute by spamming one of the shards. This also gains yourself a lot of renown for the chapter.

1a) can't see the objective (this was confirmed by the other zealot in the party)
![run_253](https://user-images.githubusercontent.com/19481783/36978703-72bbe7a2-2042-11e8-8742-3277e6c072e0.jpg)
![run_254](https://user-images.githubusercontent.com/19481783/36978708-752461b8-2042-11e8-8fcf-17c71ece55ac.jpg)

2a) can see that the objective is spammable
![run_252](https://user-images.githubusercontent.com/19481783/36978760-a1962196-2042-11e8-8380-4a001edae3ce.jpg)
![fun_008](https://user-images.githubusercontent.com/19481783/36978785-b24d0fcc-2042-11e8-992f-3e67354bf1a6.jpg)

**Comment by Lheana** [comment]
Tried, could not spam clicking on the Glass Shards.

**Comment by sioding** [comment]
fixed with patch from 31.03.2018

**Comment by Blaqwar** [comment]
The second bug (1 glass object having up to 30 charges) is still present. Some of them properly only have one charge but there's quite a few that have plenty of charges. Didn't go around figuring out which ones do and which ones don't.

![Camael_026](https://user-images.githubusercontent.com/5108812/80735347-d9522b80-8b10-11ea-8ae0-6f415f81a936.jpg)
