### ISSUE TITLE
Quest: Dogs of War

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11447]
When asked to "Investigate Koppel's Post toward the Altdorf main entrance", map tracking shows the red lake around the middle of the south side of the map (what I believe to be the main entrance)...but Koppel's is not to be found and wandering around the area and talking to the two Halberiers, two Mounted Knights, and the one Militiaman that are in the area does not flag the step for completion.

**Comment by sioding** [comment]
You are right - this IS the main entrance. You we do not have any wandering NPC at this time - so you need to have a look for something you click on. I did the quest and it works fine. I used my chance to make the hole quest - and saw that the second step was bugged. Its fixed with the next patch.

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018

**Comment by Aluviya** [comment]
This Quest seems still buggy to me, can't find any traces of Guard Koppel.

**Comment by Lheana** [comment]
It works fine. Search harder.
