### ISSUE TITLE
Isha's encouragement

### ISSUE THREAD

**Issue by gebajger** [WarEmu/WarBugs#1164]
ON live, if you used cleanse with the IE HoT already applied on the target, you had 2 HoTs  overlapping. 
Right now It refreshes itself.
Also, it could not crit .

**Comment by Zzeppenn** [comment]
Same with Shaman Green Cleanin' ^^
+ they were labeled as "Healing" type buffs, not enchantments, so they couldn't be purged by KotBS, Black Guards, etc....

**Comment by ozarmidrashim** [comment]
Fixed as of patch not long ago.

**Comment by Zzeppenn** [comment]
Well uh, it's worse now. You still can't multi-hot with the tactic, and now it does not even refresh.

**Comment by gebajger** [comment]
^^

**Comment by ozarmidrashim** [comment]
Fixed in next.
