### ISSUE TITLE
tireless honor order quest  t1 elf and misled quest norsca 

### ISSUE THREAD

**Issue by gimkus** [WarEmu/WarBugs#11697]
Tireless honor cant find end quest, misled cant find altar and talisman destroy, thanks

**Comment by sioding** [comment]
You can´t find it cause of a missing questmarker or why?

**Comment by gimkus** [comment]
tireless cant find couse cant speak with mob and see yelow quest mark on map, misled dont have talisman at all

**Comment by NorKalli** [comment]
Quest objective was not tied to correct NPC.

**Comment by NorKalli** [comment]
reminding myself to fix this in the morning

**Comment by gimkus** [comment]
high elf shadowland, healing nature quest, fill phial of dread water, say use phial from inventory but dont have that one.

**Comment by sioding** [comment]
This report is not a chance to insert any new bug you have found. Please follow our rule:
* One issue per ticket

**Comment by NorKalli** [comment]
fixed tireless honor with siodings help

**Comment by gimkus** [comment]
![image](https://user-images.githubusercontent.com/38866449/39889956-0587d968-54a2-11e8-9d87-82a1a32982f2.png)

still cant talk, tireless honor

**Comment by sioding** [comment]
No patch done - you see the fix pending label is still attached. please wait for the patch you can see in the news chapter of your forum.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018

**Comment by Tricker64** [comment]
This does not looked fixed I'm not able to complete Tireless due to same issue above I cannot Talk to NPC am I missing something ?
