### ISSUE TITLE
Boss Huntin' T2 Greenskin Epic

### ISSUE THREAD

**Issue by KriegsToddlich** [WarEmu/WarBugs#11812]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
on step 8 of this quest, talk to gnashfang...there is no turn in...he doesnt have the quest in his available list

Steps to reproduce the problem:
start t2 orc epic, get to step 8(talk to Gnashfang)

Screenshots/Videos or archive.org evidences:
![khos_000](https://user-images.githubusercontent.com/39702566/40618521-01c5ee18-624f-11e8-9f3a-b3182157410f.jpg)

**Comment by NorKalli** [comment]
fixed

**Comment by WAR2014** [comment]
yeah, the quest at stage 8 still not working. Tried to turn-in quest to NPC name Gnashfang, just like the screenshot above. Thanks

**Comment by KriegsToddlich** [comment]
still seems broken? cant seem to actually turn it in...is grayed out and doesnt actually complete
![xymox_008](https://user-images.githubusercontent.com/39702566/40871066-ef14bee2-65f1-11e8-861f-dc26a89faae1.jpg)

![xymox_005](https://user-images.githubusercontent.com/39702566/40871042-a305e260-65f1-11e8-85b3-77c1ec1f57b0.jpg)
![xymox_006](https://user-images.githubusercontent.com/39702566/40871046-aad796a0-65f1-11e8-925b-543d4c24cddf.jpg)
![xymox_007](https://user-images.githubusercontent.com/39702566/40871048-b49f0966-65f1-11e8-9511-c4999fad8a4a.jpg)

**Comment by sioding** [comment]
back to you @NorKalli  - fix pending removed

**Comment by WAR2014** [comment]
Hi, I still can't turn in the quest like above 2nd screenshot. The NPC have no overhead quest icon, and the quest gone gray. I'd tried abandon the quest once, and get it back. But still no luck.

**Comment by WAR2014** [comment]
Me again. I used /rel and the NPC appeared the quest icon overhead, but the quest gone gray not completed. Hope can fix it at next server restart. Thanks a lot!

**Comment by frankystein65** [comment]
add my name to this list.  same issue, unable to complete this stage of the quest.

**Comment by Deladriendil** [comment]
same problem (06/09/18). talk to Mobash, get sent to talk to Gnashfang, no quest icon over his head, go into the tunnels and click on the Nogaz body, go back to Gnashfang and there is a quest complete check over his head but cannot proceed, go kill Angry Nogaz outside of tunnel, return to Ghashfang, still cannot proceed.

**Comment by Barsow** [comment]
same problem 11/06/18

**Comment by sioding** [comment]
Thanks guys - we know it. @NorKalli will look at it as soon as he has free time.

**Comment by NorKalli** [comment]
while fwosh still displays the yellow quest complete, this stage has been refined to require using the rock lobber to then kill 3 mobs.

**Comment by NorKalli** [comment]
@grunbag maybe you can figure out the 'quest complete' showing when it shouldn't

**Comment by Lheana** [comment]
#8000
