### ISSUE TITLE
fort reservation

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#13536]
i was defender, screeshot first.
![fort_reserv](https://user-images.githubusercontent.com/19988772/53702272-8c10f600-3e48-11e9-8d47-c75f73269a4e.jpg)

i couldn't enter.
after expire msg, bunch of ppl in front of portal got ported.
i was in 5man grp.
half of my grp got inside after expire.

**Comment by Natherul** [comment]
there is a fix on the way that should resolve this the next patch, the reservations do seem to work however the other check is still applied when it should not.

**Comment by xaraxdestr** [comment]
still not working after patch, got disco in last phase. Could not reenter and didnt get any invader med.
![Knochenschild_010](https://user-images.githubusercontent.com/45398873/54078213-b0475980-42c4-11e9-87ed-4de747fed78d.jpg)

**Comment by sioding** [comment]
i leave this one open since we got new reports after the the patch yesterday

**Comment by Rockalypse** [comment]
My ticket was closed as duplicate so I'll post it here:
![unknown1](https://user-images.githubusercontent.com/42712833/54232588-03ffb000-451c-11e9-9ac2-186809f21341.PNG)

**Comment by sioding** [comment]
This should be fixed
