### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by Makali524** [WarEmu/WarBugs#13776]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Can't connect to server. Been trying for 20 minutes to log in and it keeps disconnecting me. I know the server isn't down. Had this issue earlier today also before I was able to log in. 

https://imgur.com/a/nkXAaWb

**Comment by Oculta** [comment]
Hello it seems the login hamsters are back ... we had this issue last week too ... maybe a restart can fix this.

**Comment by Vancerus** [comment]
I have the same issues. I renamed the "AddOn" folder and could instantly login again. So it is definitely AddOn related.

**Comment by Vancerus** [comment]
Tried to find the one AddOn by deleting one by one. Logins working occasionally, but could not reproduce with one definitive AddOn.

So my workaround was deleting the "AddOn" folder (after a renamed backup) -> logging in -> make a new "AddOn" folder and copy all in again, while logged in -> Reload ingame -> Works

Zone ports seem to work as well.

**Comment by MaxHayman** [comment]
I put in a potential fix for this earlier today. If anyone has this issue after this post please comment here.

**Comment by sioding** [comment]
fixed with patch from 06.04.2019

**Comment by MaxHayman** [comment]
Can people also provide their account name, character name and the exact time this occcured when reporting this please.

**Comment by Oculta** [comment]
Account: Oby
Character: Losgauchos
time: 04/10/19 00:25

**Comment by markytheoz** [comment]
Account: Feanor
Character: Maglor
Time: 18:04 (+9:30) 10/4/19
I don't want to spam the comments but this is happening on every single character I have.

**Comment by MaxHayman** [comment]
Hey, I put another fix in for this today. It should fix it. Please let me know. The issue before usually occurred after 12-24 hours of server uptime.

**Comment by sunspearhonor** [comment]
Account: Rant
Character: Sunspear
Time: 8:35 UTC Tuesday, April 16, 2019
Happening on multiple characters. 

I was able to login after several attempts, but the issue persists after attempting a new login. 

US player. No previous issues with logging in prior to these attempts tonight.

**Comment by Rydiak** [comment]
Account:  Rydiak
Character:  Rydiak
Time: 0440 hrs CST April 16, 2019

Multiple log-in attempts on character required before able to zone into game.  Kicked from character back into character selection screen.  Repeat process; unknown cause.  No changes on client-side for some time now (add-ons etc).

**Comment by IxanderousI** [comment]
Can confirm from me and a few guildies, they cannot get in, attempted on multiple characters on both sides, makes no difference, closing client repeatedly does not work either, i got in once earlier on then timed out from being afk, same issue again, multiple attempts, better odds winning a gold bag on a lost fort.

**Comment by asHram-HS** [comment]
Same case over here. Can't log on any of my char.

**Comment by D4W0lf** [comment]
Same issue here :
Account: DaWolf
Character: Itreksjod
Time: 18:35 EU Time April 16, 2019

**Comment by SATANICOMODERNO** [comment]
Log on to the game is impossible! I'm trying and get disconnected, even after get in the game, 10 seconds after I get disconnected again.

**Comment by markytheoz** [comment]
Kicked to server select, then character screen when trying to log in. Got in after only 3 tries but the issue is still around.
Account: Feanor
Character: Maglor
Time: 13:39pm (+9:30) 18/04/19

**Comment by sioding** [comment]
Patch done - please report new things

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019

**Comment by Feirefiz** [comment]
Hi,

I have the same disconnect problem like Disconnected1.

Account feirefiz
Character Belgaris
