### ISSUE TITLE
Gunbad: Quest: Stuck In The Middle With You

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#13808]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Can't continue this quest. After meeting the second Ghoullum and receiving the second part of the quest (Kill Redeye Big olaf), the quest simply is removed from the quest list. (Check the screenshot). 

**Screenshots/Videos or archive.org evidences:**
![Galaxyglitter_002](https://user-images.githubusercontent.com/17249318/55676313-30b4a680-58d3-11e9-9e6e-f2d7c5213f63.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by kaspn** [comment]
attempted to do this as of 4/29. first waypoint was fixed was able to complete through red eye big olaf and turn in at ghoullum(third, with the spiders), but not update the new kill, simply dropped from tome again.

**Comment by Aluviya** [comment]
This is still buggy, same problem. After the second step quest is simply removed from the tome and you can retake the quest from the first step.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
