### ISSUE TITLE
Not attached to mount Dwarf mount.

### ISSUE THREAD

**Issue by Torgrimmerr** [WarEmu/WarBugs#13810]
When you summon the dwarf mount the Dwarf hangs unattached hanging from the bottom from the mount, walking. Not all players from what I have seen have this issue but there have but there have been more the plenty i have seen to submit a report. I have a screenshot to show and my DxDiag included.

The expected behavior is for the dwarf to be firmly attached and sited in the mount not hanging and walking on the ground.

Steps to reproduce is simple get a mount of lvl  20-39 bc I'm not 40 yet I'm lvl 39 the helicopter mount. and mount it up on the dwarf in any area.

Josh

![warhammer](https://user-images.githubusercontent.com/49354178/55677123-21703180-58b0-11e9-8215-86cdc7dfe86c.PNG)
[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/3051097/DxDiag.txt)

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019

**Comment by Torgrimmerr** [comment]
#I13810  this is still not fixed, or still not working for some dwarves, My dwarf is still hanging not attached to his mount 4/14/2019 . Have updated screenshot to show. @sioding 
[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/3077630/DxDiag.txt)
![New mount](https://user-images.githubusercontent.com/49354178/56096430-f8eec580-5eb5-11e9-9475-86982950f69c.PNG)

**Comment by sioding** [comment]
It is fixed - but the client wasn't patched this weekend. Once the client files are deployed by @MaxHayman or @Natherul this will be fine.

**Comment by Torgrimmerr** [comment]
Oh ok, I though the patch was deployed bc the notes were posted already, I am sorry.
