### ISSUE TITLE
Plague on the Wind - PQ Troll Country - Stage II

### ISSUE THREAD

**Issue by Mcappucc045** [WarEmu/WarBugs#13823]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
During Stage 2 of the public quest "Plague on the Wind", the objectives require the destruction of Plague Carts and Plague Scarecrows. While I was successful in destroying the required number of plague carts, I could not interact with the plague scarecrows in the required fashion to destroy them. Right clicking on them only selected them as a friendly/allied unit, and they could not be targeted to be attacked and destroyed. 

**Steps to reproduce the problem:**
1). Enter the PQ Area for "Plague on the Wind" within the zone "Troll Country"
2). Progress through the first stage objectives by killing the requisite number of NPCs.
3). After initiating stage 2, destroy the requisite number of plague carts.
4). Once the plague carts are destroyed, attempt to destroy/interact with the plague scarecrows. 

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019

**Comment by LadyCereus** [comment]
Still having this issue after the 13/4 patch.  Destroying plague carts and scarecrows in stage 2 is not functioning.

**Comment by Lheana** [comment]
Everything works fine.
![Lheana_082](https://user-images.githubusercontent.com/11537611/56456844-672dff00-6372-11e9-8cdd-df1aec0ca5c5.jpg)
![Lheana_083](https://user-images.githubusercontent.com/11537611/56456849-6c8b4980-6372-11e9-8222-05a3bb48470b.jpg)
