### ISSUE TITLE
[Quest] Tears of Lileath

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13870]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Issue 1:
Quest shouldn't have useless rewards

Issue 2:
Quest tooltip should be:
Quest waypoint
* Rune of Dreams Read 0/1
* Rune of Forbearance Read 0/1
* Rune of Fortune Read 0/1
* Rune of Rumination Read 0/1

Issue 3:
Quest marker should disappear after reading all Runes.

Actual:
Issue 1:
Quest have useless potion as reward

Issue 2:
It's wrong

Issue 3:
Quest marker disappear after reading Rune of Dreams.

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**

Issue 1:

![Gwarnhil_017](https://user-images.githubusercontent.com/18528095/56084284-67d60b00-5e31-11e9-9b54-7db4364be5fa.jpg)

Issue 2:

![Gwarnhil_018](https://user-images.githubusercontent.com/18528095/56084285-6e648280-5e31-11e9-9d62-9d415564b8f3.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019

**Comment by Etaew** [comment]
![image](https://user-images.githubusercontent.com/4687646/63012048-6e2cd000-be81-11e9-9a84-dc25f516d465.png)
This quest seems to be still unable to be completed. Even after activating the scrolls there are no Tears of Lileath that I can see.
