### ISSUE TITLE
tactic [riposte] proccs reckless gamble

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13994]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

expected it not to procc since it is a tactic but I am not complaining. It does deal a bit of self dmg and with any m1 defence up you will spike, especially with ID out+ channeling retribution.

**Steps to reproduce the problem:**

slot riposte tactic > enable reckless gamble > parry > riposte + procc 

**Screenshots/Videos or archive.org evidences:**

haven't got any atm but can make a video of it if needed

edit: I haven't checked if  riposte/reckless gamble can procc things like flames of rhuin or WP prayer aswell. Will try to do so and update this post soon.

**Comment by rekkir** [comment]
![Rekkir_017](https://user-images.githubusercontent.com/28030187/57114167-41c4cc00-6d48-11e9-81b7-4524cb0535f3.jpg)

![Rekkir_018](https://user-images.githubusercontent.com/28030187/57114172-45585300-6d48-11e9-9356-e798ea6695c5.jpg)



as  u can see there is a lot of weird stuff going on there. I get hit by flames of rhuin, riposte proccs reckless gamble and or flames of rhuin etc.

https://youtu.be/2ywnkfdyRRQ?t=35

here u can see I got slayer m2 to procc of riposte aswell

**Comment by Nfkillz** [comment]
read patch notes https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=31511&sid=d547f3f8a163f80d0c1f400afffda5aa

Slayer :
- Accuracy will now correctly increase Flurry Radius by 5ft
- Reckless Gamble and Riposte will correctly scale with rage mechanic 
- Spine Crusher will now correctly be greyed when you’re not facing away from your target
- No Escape will now correctly show the vfx on the snared players

p.s: idk why they did it ofc its 6v6 issue lol

**Comment by Nfkillz** [comment]
the most bugged tactic
https://github.com/WarEmu/WarBugs/issues/9762

**Comment by Neil0r** [comment]
There is a sound bug with Slayer: without Reckless Gamble the attacks from Slayer don't have a real impact sound. With activatet  Reckless Gamble it's fine.

**Comment by grunbag** [comment]
Fixed

**Comment by dalen** [comment]
This is still happening.

![Falinsil_102](https://user-images.githubusercontent.com/7400/69985812-451d7180-153c-11ea-938d-0cec2893b59d.jpg)
