### ISSUE TITLE
Sentinel Weapon's proc wrong!

### ISSUE THREAD

**Issue by Galaxyshine** [WarEmu/WarBugs#14021]
The proc of the Sentinel weapon "Favor of Lileath" is set incorrectly.
You will gain 80 wounds, instead of 110 wounds.

![Galaxyshine_110](https://user-images.githubusercontent.com/50300648/57199655-d403e480-6f81-11e9-884e-0763901d0a0e.jpg)

**Comment by wargrimnir** [comment]
Tooltip is incorrect, it should be set to 80. Requires client update.

**Comment by grunbag** [comment]
fixed already

**Comment by Cimbas** [comment]
![Cimba_011](https://user-images.githubusercontent.com/16117730/85790177-14976200-b730-11ea-85a5-72cd74e4f443.jpg)

Not fixed btw
