### ISSUE TITLE
Shaman - missing healing weapon for oppressor emblems

### ISSUE THREAD

**Issue by BuzzShaman** [WarEmu/WarBugs#14026]
**Expected behavior and actual behavior:**
There's no healing weapon for shamans available from the new scenario weapon vendor in the IC.   Only a DPS one.    I assume this is not indented.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Buzzbuzz_024](https://user-images.githubusercontent.com/50312373/57207095-e3daf300-6f98-11e9-98a2-3fbda33e3f74.jpg)

**Comment by rakels** [comment]
Seems like there is one "Apostle's Blasta of Anathema" but it is declared as sword and has the wrong dps and costs (750 instead of 1500)

![image](https://user-images.githubusercontent.com/9309339/57225738-88971800-700d-11e9-880e-cf3da531f80d.png)

**Comment by NorKalli** [comment]
fixed

**Comment by BuzzShaman** [comment]
I would also add, as long as there's a fix incoming, that I think the stats on the healing scen weapon may be off.    The 2% reduced crit on this weapon makes the total crit amounts add up too 6 - which I think is too. much.   That 2% crit reduction should be changed to +6ap to keep the weapon in line with previous iterations.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019

**Comment by NihilAbalham** [comment]
Hello,
The heal weapon is still missing.
![Capuche_043](https://user-images.githubusercontent.com/19999643/57644673-ea7ef100-75bc-11e9-8e69-f69556855f5e.jpg)
Weapon besides completely useless because without AP regen so take your time ^^

Thanks !
