### ISSUE TITLE
[SW][Weapon] SC Swords incorrect classification

### ISSUE THREAD

**Issue by Siegureboy** [WarEmu/WarBugs#14033]
Conq SC swords and up have 'off-hand or main-hand' classification preventing almost all SW swords from being used as an alternate appearance, and prevents me from swapping by right clicking other swords due to classification. Not sure why last two SC swords ended up like this.

On similar note there must be a bug with new SW sc bow (lvl61): it seems to have unicorns on the ends of the bow....feel that is someones sick joke on a class they hate. Horse heads don't really make any sense on the ends of a bow, but it definitely shouldn't be unicorns.

**Comment by NorKalli** [comment]
provide me names or screenshots of exact weapons which have "main hand or off hand" so I can properly set them. The database is a big place. help me help you.

**Comment by Siegureboy** [comment]
Sorry for delay. SS of all 4 Falcata's. I didn't bother with Blades because
they are intended for SM. You rock. Btw SWs are looking for variety of
procs on weapons.

Procs I ran on live until rr65/76 sc weapons were 'Corrosion V' on my
Warlord PQ sword Falcata of Hallowed Memories, and I used a DOT with Snare
(maybe called 'Maim') on the Bloodfist Longbow T4 RvR Dwarf Influence
reward.

Boost (on hit), Marked (on hit), Aim (on hit), Corrosion (on hit),
Snare+DOT (on hit), Jolt (on hit), DOT (on hit), *Resist Debuff (on
hit)*, *Armor
Penetration Increase (on hit)*, Reactionary (on being hit), Speed boost (on
being hit), Snare (on being hit)
*italics = new proc*

I heard you deal a LOT with weapons for this game. A thought is to have
procs be craftable talismans that last a given duration. Make the materials
obtainable through RvR/SC/PVE (one option for each style of play maybe).
Each weapon that is allowed a proc, could have a special proc talisman
slot. Each proc has a level of I, II, III, IV, V etc. You control as devs
how hard it is to get the materials for specific procs and/or how hard it
is to craft them and/or each of their levels of effectiveness. More options
for players, more reason to repeat content, better player retention. High
up front work; but less afterwards: can focus on just raw stats for weapons
and just adding procs main ingredient for any new procs.

**Comment by wargrimnir** [comment]
The procs you're mentioning are only intended for armor sets, they won't be going on weapons.
Corrected the type to be main-hand only.
Unicorns however are iconic for High Elves, that won't be changing.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019

**Comment by CrimsonFenris** [comment]
![Tanaryon_060_bugappearance](https://user-images.githubusercontent.com/40425011/58570928-22329d80-8239-11e9-89c0-9e01c28b7c16.jpg)
Bug is still here, cannot use alternate appearance on SW sc weapons, wich are still erroneously labeled with "off hand". ;)

**Comment by wargrimnir** [comment]
Yeah, I'm not sure what I've been drinking. Falcata doesn't make sense to have offhand at all, neither SW or SM use them off-hand. Changed all of those next patch.

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
