### ISSUE TITLE
Enraged Beating 

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#14125]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

The broken 10 additional hatred on crit part has been "fixed" probably three times by now, but it's definetly not working as intended still. Always generates 45 Hatred, 10 of these just get added about half a second after the ability ends.

Screenshot should have shown 75 Hatred.

Expected: Generates 10 additional Hatred on crit.

Actual: Just generates 10 additional hatred when the channel ends.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/31864442/57982521-bd13c680-7a46-11e9-9783-6fe6da6911b6.png)

**Comment by grunbag** [comment]
tested on dev, and i have 75 hate if i only use enraged beating with 100% crit chance

**Comment by grunbag** [comment]
![enraged beating](https://user-images.githubusercontent.com/24207191/58364608-67f90a00-7eb7-11e9-9282-4521fdc0a2a2.png)

**Comment by grunbag** [comment]
maybe it will work better now, i found the issue. fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 25.05.2019

**Comment by Lefze** [comment]
Not fixed. It now generates the 10 additional hate regardless of critting or not.

**Comment by grunbag** [comment]
leaving as it was for now. until i can fix channels

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
