### ISSUE TITLE
New Sent WP Shield - Not correctly providing 8% Strikethrough

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#14160]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Using .getstats I was comparing between the Subjugator WP Shield and both of the new sentinel influence WP Shields. I found that I am getting the appropriate 8% strikethrough as stated on the shield, however, when I ran the same command equipped with either of the new sentinel WP shields, I found that I was not getting the 8% strikethrough as indicated in item indication. 

**Steps to reproduce the problem:**
Equip shields, use .getstat and notice that there is no provided strikethrough. Seems the difference between the Subjugator shield and the new Sent shield is that the strikethrough proc is secondary on the Sentinel shields, whereas it is primary on the Subjugator shield. I haven't had the time to fully test out the other procs.

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/14348489/58224968-768fc780-7ce5-11e9-9b43-edbe6f594bf9.png)

![image](https://user-images.githubusercontent.com/14348489/58224989-90c9a580-7ce5-11e9-998c-75413111b312.png)

![image](https://user-images.githubusercontent.com/14348489/58225053-e3a35d00-7ce5-11e9-884f-0da42c451981.png)

**Comment by dalen** [comment]
Hmm, it looks like the RR61 scenario shields have the same problem. At least "Sentry's Buckler of Reverence" that I own.

**Comment by wargrimnir** [comment]
Not sure if the order of these buffs are the issue, but I swapped them around anyway. Please confirm.

**Comment by dalen** [comment]
@wargrimnir on the Scenario shields there is only one buff though and still not working.

But subjugator buckler works, so you can probably look at that as a reference.

**Comment by wargrimnir** [comment]
Check anyway, may have been a different issue that I fixed as well.

**Comment by dalen** [comment]
It seems to have fixed it on "Bucker of Envoy" at least 👍 

"Sentry's Buckler of Reverence" is still not working though.

**Comment by wargrimnir** [comment]
I'll have to restart dev for you to check.

**Comment by keunglh** [comment]
Tried Harbinger, it seems to have fixed it there as well

**Comment by dalen** [comment]
I tested the WP scenario shields on the dev server, "Sentry's Buckler of Reverence" is fixed now, but "Shieldbearer's Buckler of Reverence" still gives no strike through.

**Comment by dalen** [comment]
Also tested the DoK bucklers on dev server now, "Sentry's Buckler of Anathema" provides strike through, but "Titan's Blood Ward of Anathema" doesn't (that second one is completely messed up btw, but I'll file a separate ticket for that).

**Comment by dalen** [comment]
here's the issues with "Titan's Blood ward of Anathema": https://github.com/WarEmu/WarBugs/issues/14269

**Comment by sioding** [comment]
fixed with patch from 01.06.2019

**Comment by dalen** [comment]
It seems like the same issue is happening with the strikethrough on the shields as with RF/SE regen ok book/chalice, like in https://github.com/WarEmu/WarBugs/issues/13226

So unequipping it and reequipping it again can fix it. Seems to especially happen when you switch from book to buckler or reverse
