### ISSUE TITLE
Estelle Meyer, Kill Collector of Dwarf chap 6 (11k 5k in Marshes of Madness)does not provide her Noteworthy Persons unlock

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1445]
Hi,
so far none of the NP unlocks are working for Order T2. 

thx

**Comment by Meralors** [comment]
I fixed this.
Durrig Olfrinson
Murdogh Kadrikson 
Barin Oathsmiter
Droki Redbeard 
Balabin Thurarikson 
Kurgan Ironfist 
Estelle Meyer 
Grunlok Steelspade 
Lokki Redbeard 
Those npc will now give tome unlock after next patch.
Can close Issue ;)

**Comment by Lheana** [comment]
Estelle Meyer, Kill Collector of Dwarf chap 6 (11k 5k in Marshes of Madness), still does not provide her Noteworthy Persons unlock.
