### ISSUE TITLE
[RP] Bloodlord runestaff has strange effect on heal and stats

### ISSUE THREAD

**Issue by Grognir** [WarEmu/WarBugs#14485]
**Issues should be unique. Check if someone else reported **
Bloodlord Runestaff has strange effect on stats and heal : it increase thoughness whereas description says it should lower it, and it increases heals whereas it has less willpower and no healing power than my healing staff

**Expected behavior and actual behavior:**
When I am equiped with "apostle's runestaff of reverence" (having a +23 toughness talisman), my total toughness is 222.

With a bloodlord runestaff with any toughness talisman my total toughness should be at least 199 (even lower do to description), but it reaches 298.

Effect on heals is also very strange:

With apostle's runestaff i have 742 willpower, 78 healing power and 164 healing bonus and my Grungni's gift reaches 455 (see last line of combat tchat box in first picture)

By switching only the staff with bloodlord runestaff I have 677 willpower, 36 healing power and 142.6 healing bonus and my Grungni's gift reaches 490 (see last line of combat tchat box in second picture)

Picture 1: apostle'runestaff
![Grognur_024_apostle's staff](https://user-images.githubusercontent.com/44229673/60288616-e3b20080-9914-11e9-946c-69ff7c918bc5.jpg)

Picture 2: bloodlord runestaff
![Grognur_023_bloodlord staff](https://user-images.githubusercontent.com/44229673/60288644-f593a380-9914-11e9-8f78-3f5ee1b6933b.jpg)

**Steps to reproduce the problem:**
Just switch runestaff

**Comment by sioding** [comment]
Just wanna be sure: you also checked your papedoll/addong numbers agains the .getstats ?

**Comment by Grognir** [comment]
Yes same value than addon

**Comment by grunbag** [comment]
fixed

**Comment by Aluviya** [comment]
![Aluvya_058](https://user-images.githubusercontent.com/17249318/61380368-87098c00-a8a9-11e9-8e7d-6f49195243c8.jpg)
I would like to reopen this case, this seems still buggy to me. The tooltip of the Staff says it reduces armor+toughness but in addition to that - it also reduces heal by 5 % (as far as i can recall this was the previous tooltip to this staff) - gestats also reporting healing output was 0,95 % which is exactly the numbers on the screenshot posted. Bloodlord Weapons either need an updated tooltip or the hidden malus needs to get removed or at least restored to 100 % healing output. With this patch it seems healing was nerfed from 105% to 95 % .Also same case is for WL-Weapon (and probably many other Bloodlord weapons -which doesn't really matter healing wise on WL - but has also that hidden healing malus)

**Comment by grunbag** [comment]
No hidden debuff

**Comment by grunbag** [comment]
Probably due to willpower on your other staff

**Comment by Aluviya** [comment]
I told you, i had no staff equipped. There is a hidden outgoing healdebuff of 5% exactly

**Comment by grunbag** [comment]
Fixed with next patch
