### ISSUE TITLE
Talisman window

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#1457]
Seems to be a bquite a few bugs with the talisman making window. I cant quite tell you what the reason is, but what happens is that fragments dont register in the window at some point and then i cant clear it to start over. Have to log out to reset it. 

Sometimes i can make 20 tallies before it happens, sometimes its bugged instantly. 

I do mix levels of ingredients... maybe that could be it?

**Comment by Evildoor** [comment]
I doubt the last sentence. Mixing different levels of materials was always a normal practice to adjust the talisman level.

**Comment by s0undie** [comment]
I agree, just seems like it sometimes could be the reason...

**Comment by s0undie** [comment]
It seems to bug out at the same time as i get the combat bug for joining scs... Weird i know.

**Comment by M0rf** [comment]
I have had the same issue with gold dust aswell as fragments, moving the item that doesnt register to a different bag fixes it, so if it is bugged in your main bag move the item to your crafting bag or vice versa.

**Comment by Reggaewaldo** [comment]
@Evildoor It could be an issue with the calculation when using materials of different skill.

@s0undie "It seems to bug out at the same time as i get the combat bug for joining scs... Weird i know." You think you could just try the &jump to see if that gets it working again ? If it is related in some way. Long shot perhaps but I have seen stranger things :)

I'm going to add that we need a confirmation on this and hope more people will report it, should be widespread.

**Comment by shamallow** [comment]
" Have to log out to reset it " : hi, i have the same problem and log out resolve it.

**Comment by vove-RoR** [comment]
Probably related:
http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=10477
#1996 

Happens with apothecary as well. Basically when you craft bundles of items once you run out of 1 ingredient the UI glitches BUT it seems to only happen if you spam that crafting button really fast.

**Comment by Luth-RoR** [comment]
Should be fixed, as the server checks for legit mats in the crafting slots now, so that there is no difference between the client and the server slots anymore.

**Comment by LordMort** [comment]
Hi there!

I just wantedd to say that this issue still persists.

I have the same problem with all of the compounds (alchemical, aggregate, elemental, as well as terrestrial) I tried. Upon trying to put the compound into the main ingredient slot the apothecary skill becomes unusable until I log out and log back in again.

**Comment by LordMort** [comment]
I want to add the following observation / remark and question:

The compounds are available at the guild craft merchant only. Is it possible that this has something to do with this issue?
