### ISSUE TITLE
Shadow Warrior Melee Sword Skill bug

### ISSUE THREAD

**Issue by myst187** [WarEmu/WarBugs#14905]
I create a new character, Shadow Warrior and I cannot equip my starting sword, i do not have the Skill to equip swords

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Cattybri_000](https://user-images.githubusercontent.com/55065861/64495086-e311e080-d25a-11e9-845a-8253ec896a7b.jpg)

**Comment by Ethelord23** [comment]
![Esseral_000](https://user-images.githubusercontent.com/55454892/65061140-f8d18500-d981-11e9-871a-ba3d571755c7.jpg)
I have the same problem !

**Comment by grunbag** [comment]
Should be fixed with next reboot

**Comment by dbddhkpuka** [comment]
It seems to be fixed when you create a new char according to the info here:
https://www.returnofreckoning.com/forum/viewtopic.php?f=76&t=33422#p376298

I still have the problem of wrong item restrictions and thus it stays the same.

[https://cdn.discordapp.com/attachments/329292495336767488/623232864103956480/unknown.png](url)

**Comment by dbddhkpuka** [comment]
Can a team member provide a clarification of this please?
--> https://www.returnofreckoning.com/forum/viewtopic.php?f=76&t=33422&p=376589#p376589

Since players seem to have created toons during the past 3 (?) weeks that have this issue, and new ones don't, rerolling these toons doesn't sounds like an appropriate "fix".

I imagine that some kind of template in the database is used when creating a new character, on which the value of the usable equipment has been wrong, and thus it should be able to be corrected also on the existing ones. Wild guess, yes, but technically possible.

**Comment by wargrimnir** [comment]
Rerolling is the answer
