### ISSUE TITLE
Butchering

### ISSUE THREAD

**Issue by Stinkypants** [WarEmu/WarBugs#1511]
The lizard mob will drop torn scale for armor potions but they also drop something else not in the database.  It shows up as a black box icon with the words "no loot" and is unclosable. You have to outdistance the mob to get to box to close, very curious.

**Comment by Tyramissoux** [comment]
There is no butchering profession yet- you're talking about scavenging. You can't scavenge animals. If you do, exactly what you described will happen.

**Comment by ropuch** [comment]
The butchering profession is available. Described problem shows up on all lizard mobs (in all tiers/area).

**Comment by nalgol** [comment]
lizzard thoungs where missing in db i added them to dev server should be fixed on live with next update

**Comment by ropuch** [comment]
I think there's more to this than just lizzard thoungs missing from DB.

I've checked all "items not in DB" and have a few observation.
- it's several items shwowing with no icon, that can't be picked up (info gathered with /craftvaluetip digest command, CraftValueTip Addon, number in [] is uniqueID field):
[186850]Enslaved Pack Mule
[84059]Whispering Pyre Ivy Seed lvl0/0 craftingBonus{5=3,9=125,14=4,13=18,}
[2010868]Stompas of Conquest lvl16/0 bonus{1={t=2,v=19,cTL=nil,r=5,tCT=nil},}
[87487]Thin Lizard Hide lvl0/0
[84225]Prickly Goldweed Seed lvl0/4 craftingBonus{5=3,9=1,14=10,13=16,}
[157861]Draught of Allaying lvl1/4 bonus{1={t=3,v=0,cTL=0,r=7872,tCT=180},}

- RND for lizard's loot seems to be kinda broken, if non-pickable items show up, the come in "waves": first several [84059] in a row, then several [84225] in a row, almost never mixed up

I don't know how your DB work looks like, but I assume having uniqueID for item-related bug can be helpful (it looks like PrimaryKey). Since CraftValueTip addon is available, I could post some hints on forum how to use it to provide

**Comment by mursie** [comment]
this is still broken.  Lizards are being butchered with a no-icon loot box popping up that can't be closed (i was in Troll country butchering lvl 12 - 14 salamanders).  Happens with just about every lizard.  Have to just get out of distance of mob body before the box will finally disappear - and you don't get any butchered item or complete the butchery when you do this (i know because im trying to level it atm).

**Comment by k0mode** [comment]
I think the most hard problem of butchery is lack of duration components that dropped usually from boars. But now no duration components from boars, The same with energy components btw. Will it be fixed up?
