### ISSUE TITLE
Order Quest - Horrors of War

### ISSUE THREAD

**Issue by tophbuddy** [WarEmu/WarBugs#15517]
Completed all objectives of "Horrors of War" question. Completed orange quest marker is above Sergeant Westwood, but when "completed" is clicked, nothing happens

**Comment by Lheana** [comment]
Try to abandon the quest and retake it.

**Comment by tophbuddy** [comment]
I did, but then got the same issue. I did notice that the objective to rally the "Cowering Militiaman", talking to them completed the objective, but they did not react correctly so I think that might be part of the reason why the quest won't turn in

**Comment by Lheana** [comment]
Screenshot please.

**Comment by tophbuddy** [comment]
![Horrors of War 5](https://user-images.githubusercontent.com/35351543/72925266-42065c80-3d07-11ea-8765-a230bec269d8.PNG)
![Horrors of War 6](https://user-images.githubusercontent.com/35351543/72925267-42065c80-3d07-11ea-9359-14ebb71cfe36.PNG)
![Horrors of War 7](https://user-images.githubusercontent.com/35351543/72925268-42065c80-3d07-11ea-9ad8-6d6c4b305e82.PNG)
![Horrors of War 8](https://user-images.githubusercontent.com/35351543/72925270-429ef300-3d07-11ea-83cb-eaf4700b288d.PNG)
![Horrors of War 1](https://user-images.githubusercontent.com/35351543/72925271-429ef300-3d07-11ea-892b-c8c84d2cdb23.PNG)
![Horrors of War 2](https://user-images.githubusercontent.com/35351543/72925272-429ef300-3d07-11ea-92a0-3a1d5c1b8aa9.PNG)
![Horrors of War 3](https://user-images.githubusercontent.com/35351543/72925274-429ef300-3d07-11ea-8248-add6b360719c.PNG)
![Horrors of War 4](https://user-images.githubusercontent.com/35351543/72925276-429ef300-3d07-11ea-80b5-a3f9dbf842dc.PNG)

**Comment by tophbuddy** [comment]
![Horrors of War 1](https://user-images.githubusercontent.com/35351543/72925334-5e09fe00-3d07-11ea-8897-0545befa3f11.PNG)
![Horrors of War 2](https://user-images.githubusercontent.com/35351543/72925343-64987580-3d07-11ea-8a21-bcb51e8bfbcf.PNG)
![Horrors of War 3](https://user-images.githubusercontent.com/35351543/72925350-66623900-3d07-11ea-9431-b124345a309c.PNG)
![Horrors of War 4](https://user-images.githubusercontent.com/35351543/72925354-682bfc80-3d07-11ea-9e8b-f2cd1a897c26.PNG)
![Horrors of War 5](https://user-images.githubusercontent.com/35351543/72925362-695d2980-3d07-11ea-94e4-52dcbe02ddfc.PNG)
![Horrors of War 6](https://user-images.githubusercontent.com/35351543/72925367-6b26ed00-3d07-11ea-9859-f8cd309ed7fd.PNG)
![Horrors of War 7](https://user-images.githubusercontent.com/35351543/72925369-6c581a00-3d07-11ea-907b-f2a0e0c31f89.PNG)
![Horrors of War 8](https://user-images.githubusercontent.com/35351543/72925374-6e21dd80-3d07-11ea-81e8-5f1d0cd8bb09.PNG)

**Comment by tophbuddy** [comment]
The last photo is after pressing complete and the quest doesn't turn in. Did this quest again after abandoning it

**Comment by Lheana** [comment]
Wait for a server restart to see if it fixes it. But I tested this quest, and it worked fine.

**Comment by Lheana** [comment]
I think I know where the issue comes from. I already fixed it, just wait for a patch.

**Comment by tophbuddy** [comment]
Thank you! I will update if I still get an issue after the next patch

**Comment by Natherul** [comment]
should be fixed as of today
