### ISSUE TITLE
pack hunting with trained to kill stance ( WL bug)

### ISSUE THREAD

**Issue by Gwelthaz** [WarEmu/WarBugs#15722]
Saw a white lion with Trained to kill stance (guardian) and the AA Haste tactic (pack hunting)proc from "trained to hunt"

Tried it couple month ago on my wl to check it.
i manage once, but i dont know how i did it.
Putting Trained to hunt and slot the tactic pack hunting, then switching stance to trained to kill and still benefit the pack hunting tactic.
I saw a white lion yesterday with it again, i though it was fixed as i told Yalikska couple months ago

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Farlopa** [comment]
shoud be linked with that one cause still not fixxed since 29 of November

**Comment by Farlopa** [comment]
https://github.com/WarEmu/WarBugs/issues/15208

**Comment by grunbag** [comment]
fixed

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
