### ISSUE TITLE
Sovereign Warlord BLORC 8th bonus missing

### ISSUE THREAD

**Issue by Tark100673** [WarEmu/WarBugs#16119]
Hi all,

I have completed the SOV Warlord set (the main one) for my BLORC, but i cant find the 8th bonus, that should be a granted ability. 
I checked in the character ability window and in the Granted Ability window in UI but i cant find any new ability there.
Ty

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Tark100673** [comment]
The 28/03 patch didnt resolve the issue. I cant find any new ability in Granted Ability UI window.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
