### ISSUE TITLE
[AM] True magic is not increasing range still even after fix 

### ISSUE THREAD

**Issue by Zaldra5** [WarEmu/WarBugs#16183]
I am reposting this because my previous bug tracker was closed saying it was fixed after I posted it still was not working

True magic is the 8 piece bonus from the Sovereign set for Archmages from cities, only just got the final a day or so, but the ability seems to not be working.

so most of the DPS abilities of the Archmage are 100ft range this when the ability is used it should increase the range of all abilities by 20% for 10 seconds which should be 20 more feet but it just seems to go on cooldown and do nothing.

Its fairly easy to test, just find max range then take a step or two more than use True magic

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Zaldra5** [comment]
Tested it with the patch it extends the range of healing abilities, Energy of vaul and balance essence, but still isn't increasing the range of my dps abilities like it says it should

**Comment by grunbag** [comment]
It works with all abilties for me

**Comment by grunbag** [comment]
without the buff , as you can see i"m at 112 ft of the target (check chat log)
![without tactic](https://user-images.githubusercontent.com/24207191/78806052-7dd5c780-79c2-11ea-9db2-60ce2c8a42eb.png)
then keeping same position and distance an use the buff :
![with buff](https://user-images.githubusercontent.com/24207191/78806130-92b25b00-79c2-11ea-9e9c-858555c39bb6.png)
