### ISSUE TITLE
Problem to stay in combat with healer

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#17818]
**Expected behavior and actual behavior:**
Stay in combat while i have hots on targets.

**Steps to reproduce the problem:**
Enter in combat and try to stay that way healing
Leaving the combat make you lose morale constaly.

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/rN9N8Qojwy8

**Comment by Rydiak** [comment]
You were gaining morale throughout that entire video. Also, merely refreshing HoTs on someone will no longer keep you in combat.

09/09/20 patch notes:
[Misc]

- Fixed an issue with combat flagging when healing others.

**Comment by notre4ror** [comment]
Look again, i'm hoting ppl "on combat" and ppl "out of combat".

During the "+/- combat" you stop gainig morale (i still get some thanks to the tactic i have sloted if i heal crit just before the -combat).

Anyway the issues is to stay in combat while i'm normally healing, wich is motsly with hots.

And yes i was expecting to get in combat if someone has my hot and is still in combat coz is the way the healers get in combat (is the base system of the game).

Now i'm getting out of combat after putting a hot wich is wrong.

**Comment by Kaelang** [comment]
"Now i'm getting out of combat after putting a hot wich is wrong."

This was patched recently and is working as intended.
