### ISSUE TITLE
Sentinel Talisman can be put into all gear now

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#18348]
Sentinel Jewel can be slotted into Bloodlord Weapon edit: Oops its all gear
![image](https://user-images.githubusercontent.com/21229715/104763532-a8ac3380-572b-11eb-9ed6-a0dfa8efef12.png)
![image](https://user-images.githubusercontent.com/21229715/104763765-05a7e980-572c-11eb-9362-af54c1565e17.png)

**Comment by Lithenir** [comment]
In exchange for that you cannot slot ANY talisman in your sentinel jewelry. Not even normal talismans

**Comment by duvalx** [comment]
yes i can second this, i cant use the talismans in the ring slot.. infract nothing will fuse to the ring,  also when i look in the tome the ring part of the reward is missing! this is the same on both my characters that have the ring... but it is still showing as a reward on all my other characters that do not have enough influence.

**Comment by duvalx** [comment]
![Fatchucknorris_000](https://user-images.githubusercontent.com/77515403/104786752-c1e1ce00-5785-11eb-9c2c-cc99b0ebbdfe.jpg)
![Fatchucknorris_001](https://user-images.githubusercontent.com/77515403/104786756-c5755500-5785-11eb-9532-3563671e85e3.jpg)
hope this helps

**Comment by MaxHayman** [comment]
This is fixed as of now. The slots placed into invalid slots should be popped out.

**Comment by Sixmoons48** [comment]
It isnt fixed yet Max, just tested on my gloves and was able to slot block%
