### ISSUE TITLE
Razor Strike Incorrect Animation  

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#18367]
Witch Hunter Ability Razor Strike's animation is that from Burn Heretic!. A Torch Spawns and hits the target instead of the rapier sweep
![Ostwin_000](https://user-images.githubusercontent.com/53047875/104962045-976e5b80-59a5-11eb-83f4-0be39f777712.jpg)

**Comment by Lnternsmite** [comment]
![Ostwin_001](https://user-images.githubusercontent.com/53047875/104962140-cedd0800-59a5-11eb-84fa-58aa3b01996c.jpg)

**Comment by CrimsonFenris** [comment]
Was about to report it as well, see screenshots below.

ps : @Lnternsmite : you should add the [WH] tag to your post title for better sorting. ;)

Razor Strike animation :
![Razor_Strike_Anim](https://user-images.githubusercontent.com/40425011/105053709-8a1ea300-5a71-11eb-8d10-d390a2b24f06.jpg)

Burn Heretic ! animation :
![Burn_Heretic_Anim](https://user-images.githubusercontent.com/40425011/105053660-7d01b400-5a71-11eb-9157-64fa8e87c031.jpg)

**Comment by Raught19** [comment]
+1 can confirm as a lvl 1 new witch hunter as well. It also seems like its either due to the animation, but the damage is very lagged on it. Compared to other abilities.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by CrimsonFenris** [comment]
Actually animation is still the same as Burn Heretic, some mishap in the today's patch maybe ? ;)

**Comment by Raught19** [comment]
Confirmed animation is still Burn Heretic

**Comment by Grock-r** [comment]
The issue still persists, last attempt to fix changed nothing

**Comment by lilimx** [comment]
Issue still persists
