### ISSUE TITLE
scenario weapons (T3 patch)

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1877]
The price of shaman magic sc staff is wrong. No idea if it is visual bug or really the price is lower but nevertheless it is bug
<a href='http://postimage.org/' target='_blank'><img src='http://s24.postimg.org/k2dkfk1at/weapon_price.jpg' border='0' alt="weapon price" /></a><br /><a target='_blank' href='http://postimage.org/'>imgupload</a><br /><br />

**Comment by Evildoor** [comment]
Staff mentioned above is also 1handed, should be 2h.
Some more problems with SC weapons:
All shields with Shieldbearer's prefix are too cheap (all tiers).
Sentry's Stabba of Cruelty/Ferocity - are 2handers with 2hander prices.

**Comment by genisaurus** [comment]
Fixed all Staffs to be 2-handed
Fixed pricing on Staffs to match 2-Handednss (T1-T3)
Fixed pricing on Shieldbearer's Shields (T1-T3)

**Comment by Evildoor** [comment]
For some reason Sentry's Stabba of Ferocity was not fixed. Asked @Meralors, he fixed it. Will be pulled live in next patch.
