### ISSUE TITLE
Fighting Fire With Fire quest

### ISSUE THREAD

**Issue by zabis** [WarEmu/WarBugs#1901]
Halbjorn Frent NPC cannot be found in Volgen.  This is the first NPC in the questline for the Stalker Shoulders for Destruction.

**Comment by Meralors** [comment]
He's inside a house in Volgen ( the one next to the mailbox ). I'll check if he's there on live as soon as I can log in... :D

**Comment by genisaurus** [comment]
This should be fixed next patch, if it's not already.

**Comment by mursie** [comment]
as of 2 mins ago - still not at volgen (not in house either).  Just updating
