### ISSUE TITLE
Foreman Stonebrow

### ISSUE THREAD

**Issue by Stahn456** [WarEmu/WarBugs#19464]
Foreman Stonebrow in Black Fire Pass used in Skulls of Succession quest from Karak Eight Peaks is currently spawning as Unattackable at approx 47k, 46k inside the mine. His hero partner has no issues dying. GM Siolor appeared and confirmed the issue could not be resolved by aoe on the area and attempted to respawn him by killing him to see if that fixed the issue. It did not.

**Expected behavior and actual behavior:**
Target can be selected but not attacked.

**Steps to reproduce the problem:**
Automatic upon npc spawning.

**Testing Screenshots/Videos/Evidences (always needed):**

![Consternation_000](https://user-images.githubusercontent.com/79117022/134794453-5c007b91-979b-4baf-b8eb-a6adf8400ad4.jpg)

**Comment by ekalime** [comment]
His state has been fixed and he will now be attackable and attack back.

**Comment by Stahn456** [comment]
Unfortunately, it still isn't fixed. I have another screenshot here as evidence
![Consternation_001](https://user-images.githubusercontent.com/79117022/134822117-f41cc831-9728-45e2-bf56-71390a293ea3.jpg)
e.

**Comment by Lheana** [comment]
ekalime meant that it's fixed on dev server, and will be fixed with next patch, that's why there is the "Fix Pending" tag on the ticket and the ticket has not been closed yet.

**Comment by Zomega-WAR** [comment]
Confirming that he is now attackable and gives credit for the quest. Thank you for the fix.

**Comment by lilimx** [comment]
Fixed with Patch 01/10/2021
