### ISSUE TITLE
BB/BE bosses do not drop loot upon death and no quest goal is being updated

### ISSUE THREAD

**Issue by unflaggmyaccount** [WarEmu/WarBugs#20127]
[since for some reason github marked my account and flagged, i will repeat ticket from one more account]
Upon killing boss in BB/BE boss do not drop any gear as well quest goal is not being updated. Faced this twice on this week on two different bosses in different runs:
- Bartholomeus the Sikcly in BB one run. I haven't done BE the same day, since ppl got disappointed by not getting soulstone quest updated and left party,
- Barakus the Godslayer in BE the other day.

I have not noticed this happen on same bosses twice so far, so might be a floating bug. Meaning that during two different runs, I have faced it on different bosses. Influence seems to be still rewarded though.

**Expected behavior:**
- Upon killing the boss drops set gear.
- Upon killing boss, quest goal is being updated. For example number of boss needed to be killed for reward increased.

**Actual behavior**
- No set gear is being dropped.
- Quest goal is not being updated.

**Steps to reproduce the problem:**
- Kill the boss in BB/BE dungeon

Testing Screenshots/Videos/Evidences (always needed):

Did whole dungeon run, but quest goal was not updated for Barakus the Godslayer.
![image](https://user-images.githubusercontent.com/106101045/169881225-cc0d0f80-18b5-48e9-94d2-5125acba23c7.png)

**Comment by unflaggmyaccount** [comment]
This seems to be related to this issue. One person in my party noticed boss killed itself. 
https://github.com/WarEmu/WarBugs/issues/20106

**Comment by lilimx** [comment]
Hey,

guess it's more related to this issue: #20039

**Comment by unflaggmyaccount** [comment]
> guess it's more related to this issue: #20039

It is possible they are both related. No lockout and no quest reward, might be due to bosses kill themselves.

**Comment by keunglh** [comment]
Also wanted to reiterate this issue for Barakus from BE. 2 days in a row the kill did not count for either the Gear piece or the Soulstone quests, no influence gain, no gear drop. Lockouts were checked.
![image](https://user-images.githubusercontent.com/14348489/171421276-fc1fdf96-5276-4356-9e5b-e49cf7b1964a.png)
![image](https://user-images.githubusercontent.com/14348489/171421329-6a16d52e-41ab-439c-b7a9-726d68de4f83.png)

**Comment by Syzako** [comment]
Quest canceled and retaken. Tried a third time, same problem.

**Comment by Syzako** [comment]
Tried for the fourth time (2022-06-05). "Kill" works, quest completed.

**Comment by lilimx** [comment]
Fixed with Patch 29/06/2022

**Comment by tfargh** [comment]
Not fixed. Didn't get loot, didn't get quest completion for the talisman quest.
