### ISSUE TITLE
Focused Mind - wierd behaviour

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#2204]
[Zealot] The Morale 2 Focused Mind often bugs out for no apparent reason. While the snare and silence immunity seems to work fine, about 50% of the time the casttime does not decrease. Instead, the castbar shows the intended casttime, but the actual cast gets stuck at the end animation.

I am not able to determine why the ability sometimes works and sometimes doesn't.

**Comment by RoR-Zomega** [comment]
Confirming that when using Focused Mind on my Zealot often the cast time reduction doesn't get applied. I haven't been able to find a way of replicating it :(.

**Comment by ozarmidrashim** [comment]
Was fixed in recent patch (reduction / subtraction stat problem.)

**Comment by RoR-Zomega** [comment]
This bug is back again. I've been experiencing it in dungeon boss fights (i.e. with the Terror debuff) regularly for a while now but I have no way of reliably replicating. The silence and anti-CC part works but no buff gets applied to your character to trigger the cast time reduction.

**Comment by Kaelang** [comment]
I will re-open this issue pending further investigation. Please can you draft further information as to what the situation was when you encountered this problem.

**Comment by RoR-Zomega** [comment]
Sorry for the delay, haven't done much PvE recently.

I encountered this bug again during a Bastion Stairs run today. We were on the final boss of mid wing (giant Bloodthirster in the ring of fire). I was on a Zealot. The boss fight had been going on for a long time and I had plenty of morale built up for M2 Focused Mind. Seeing as the group was close to wiping I used the ability in order to get the cast time reduction buff. However, all that happened is that the morale was consumed and the skill went on cooldown.

I didn't notice the Focused Mind buff appearing on my buff list at all, but if it did appear then it would've been for a split second at most as I followed up the M2 with group heal which still had the full cast time. I checked my buffs during the cast and Focused Mind wasn't on there.

That's the general situation every time it fails for me in PvE. Pop it for the cooldown reduction but the Focused Mind buff that lasts for 10 seconds isn't applied. The cooldown reduction isn't working "in the background" either - the skill just flat out fails to do anything except consume morale and go on cooldown.

I've only noticed it happen during boss fights, but then the only time I ever need to use the skill is during a boss fight going badly so it might bug out at other times as well.

Some anecdotal evidence is that I've heard Sorcs often encounter the same issue if using the skill during boss fights.

**Comment by XmatXergon** [comment]
This one can be closed.
Focus Mind is disabled on some boss fights to not allow player ignoring mechanic.

**Comment by Zomega-WAR** [comment]
In which case, the current way of doing it by having FM usable but fail and expire imediately with no message is to actually disable the morale itself (much like Terror disables res) if possible, or add a new debuff stating that Focused Mind is disabled.

Better yet, if it's just the CC-immunity that is an issue then please at least allow the AP and cast time reduction to apply as to be honest most times I would use it was because I needed better healing and not because I was trying to cheese a boss mechanic.

Either way, some kind of player feedback to state why FM can't be used or is wiped instantly would solve a lot of the confusion because currently it just looks like a bug.

**Comment by XmatXergon** [comment]
I agree, it may be patched soon to provide certain information when player tries using that Morale, we will see.
