### ISSUE TITLE
Futile Strikes 

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#2332]
No longer works since Skaventide

**Comment by ozarmidrashim** [comment]
Fixed

**Comment by Evildoor** [comment]
Still not works according to #2344. Bugged again, or fix not implemented yet?

**Comment by ozarmidrashim** [comment]
Missing handler name
