### ISSUE TITLE
Evermourn Scholar Mage

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2387]
Evermourn Scholar Mages, level 28-29.  Location: Evermourn Mansion in Saphery 20k 26k.  The mobs have no model, just a floating staff.

**Comment by Meralors** [comment]
They were invisible and half sized, so cute elf :p 
Its fixed now and will be live next patch :)

**Comment by ElMosquito** [comment]
This problem is back with the same mobs at the same location.
![EvermournScholarMage](https://user-images.githubusercontent.com/16590792/54675198-60effd00-4afe-11e9-973d-80d23b91b1b0.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
