### ISSUE TITLE
QUEST BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2390]
![123](https://cloud.githubusercontent.com/assets/16375224/11929474/f561ff86-a7e3-11e5-9ce1-e2905f21f226.jpg)

I click on complete and nothing happens...i logged out and tried again but i cant pass the quest :/ Is this a RANDOM nasty bug or what? No...i even exited the game/restarted my Pc...logged in again and cant complete it...i click COMPLETE and nothing happens :(

**Comment by Stefanosgr18** [comment]
![123](https://cloud.githubusercontent.com/assets/16375224/11929784/9fca3036-a7e6-11e5-9e41-df47bc8caf0d.jpg)
This quest too...i press Complete and nothing happens...why? OMG...:'(

**Comment by Stefanosgr18** [comment]
Yes...these 2 quests so far are bugged for me...i had to abandon them...

**Comment by noisestorm** [comment]
Can confirm for the First One. Tested with Slayer. XP+Item are aquired (can be completed). On AM there is just XP, no Item and quest cannot be handed in.

**Comment by Stefanosgr18** [comment]
Dont know what causes it...so far only these 2 quests i couldnt complete...everyother quests so far (7 level) works flawless!

**Comment by Meralors** [comment]
I'll look into it, probably just no selectable reward for archmage but you need to select one to complete quest.

**Comment by Meralors** [comment]
Fixed both, live next patch.

**Comment by Stefanosgr18** [comment]
@Meralors You are the best human in the world for today...and trust me...its truth! Thank you sir...keep fixing little stuff so we get the GAME where it belongs!

**Comment by Stefanosgr18** [comment]
Not Fixed yet...maybe you didnt applied it with latest patch? :/

**Comment by Meralors** [comment]
If its not in patch note its not applyed on live :)
Last big update was 18/12, I don't know when next one is coming

**Comment by Stefanosgr18** [comment]
Ok thanks anyway for fixing this...its really important to not breaking the quests chain :+1:
