### ISSUE TITLE
no noteworthy persons unlocks in Dwarf Order.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#3791]
Hi, I am reporting no Noteworthy persons unlocks in Dwarf as Order both Badlands and BFP.

**Comment by DanaBloodkiss** [comment]
Thank you for the report!
Note for Devs: This will be fixed in one step in all zones.

**Comment by Meralors** [comment]
If I remember well when I added noteworthy persons unlock I couldn't find info about them in dwarf T3. But I may be wrong :)

**Comment by DanaBloodkiss** [comment]
Fixed in next.

**Comment by gittoaster** [comment]
Some entries still not working 
(order) BV - Elgaroth Karginson, Thane Karrasteel (both in Thane's Defense).

**Comment by Meralors** [comment]
I fixed those 2 new NPC.
ToK unlock will work with next patch.

**Comment by gittoaster** [comment]
Cool.  I also noticed some in Badlands
Lungnie the Dour
Skaf Copperstone
Doragrum Stouthammer

**Comment by Meralors** [comment]
Lungni the Dour was already fixed. I added ToK unlock for Skafcopperstone and Doragrum Stouthammer
