### ISSUE TITLE
relentless siege quest wrong description

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#3802]
either description or kill count is wrond. one says 99 kills, other 45 kills.
![tiggo_007](https://cloud.githubusercontent.com/assets/13809443/12378619/f67ca496-bd43-11e5-88d4-dcbd9432b4c3.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch. Killcount is at 99 now.

**Comment by Soulwhisper** [comment]
![bug](https://cloud.githubusercontent.com/assets/16864486/12629871/5c71f0f6-c552-11e5-877f-bb6aa096746a.jpg)
Still bugged.

**Comment by Evildoor** [comment]
It seems that you logged onto a character who still had an old version of the quest. I'm sure that next time it will be the proper quest with 99 kills.

**Comment by Soulwhisper** [comment]
Nope...it still says /99 in ToK.
![toufekiaaaa_073](https://cloud.githubusercontent.com/assets/16864486/12913289/7879f96e-cf26-11e5-9ee5-870dc76af669.jpg)

**Comment by Torquemadra** [comment]
Weird one, should be fixed next patch

**Comment by Soulwhisper** [comment]
![phantomas_018](https://cloud.githubusercontent.com/assets/16864486/13191399/15620ef4-d76c-11e5-9d48-89ff2dd536eb.jpg)
Not fixed yet. :P Just took it with my new character for the first time. Waaagh!

**Comment by Soulwhisper** [comment]
![phantomas_001](https://cloud.githubusercontent.com/assets/16864486/13215049/6df91ecc-d95b-11e5-85c3-03ba47bef6c9.jpg)
So is this suppose to have /99 kills? If so lets close it.
