### ISSUE TITLE
Beastiary: Plague Victim - Epic Epidemic

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3875]
Mathis Rittenhouse (18k,48k in Norsca) does not give unlock for Destro side. I haven't checked if Order, Sister Raffaela at 51.5k,57k, works or not...

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Shadowsmove** [comment]
the order side does not work, just for your information.

**Comment by Evildoor** [comment]
Logical. The ticket is still not closed and it was not mentioned in the patchnotes.
