### ISSUE TITLE
[Quest] The Dark One

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3877]
Turn in Brandr the Grey. The requirement is mixed up with Hap Lesterson.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.

**Comment by Laurell-Silentshade** [comment]
Still broken. Requirement now says speak to Gunnolf Geirgnash.

**Comment by DanaBloodkiss** [comment]
It's working correct on Dev Server also I fixed the bug causing this (easy fix) shouldn't be bugged anymore. Maybe some missing table which needs updating. Wait for next Hotfix.
