### ISSUE TITLE
Alliance Issue

### ISSUE THREAD

**Issue by Zorbibroz** [WarEmu/WarBugs#4528]
Hi, i have a problem to form an alliance with a friend. 
My guild is level 8 and theirs level 10.
I try with the Alliance's Onglet in Guild Interface and with command but nothing work.

My guild is Anathema and i want to make alliance with CCM.

I hope that's will be fix soon :)

**Comment by zernichter** [comment]
Hi,

we've the same problem, we cant from an alliance with our "partnerguilds".
we tried almost everything, changed the Guildleader several times, kicked / reinvited Guildleader and so on. No result.  would be really nice if someone would check whats that all about..

here our Guildnames  that are unable to join / form the alliance.
"Gothic Society", "Beware" & "Like it Hard"

so long..

**Comment by zernichter** [comment]
solved :) it finally worked !

**Comment by Vigfuss** [comment]
Same issue for CA guild

**Comment by Natherul** [comment]
I just ended up in this situation as well, I wonder what did you do to make it work all of a sudden?

**Comment by wiscel** [comment]
Same here, still can't form an alliance.

**Comment by Astalan54** [comment]
I know I've been referenced here, but I have also tried passing guild lead to another guildie, as has the other leader I am trying to form an alliance with, and to no avail. My guild is The Crucible and his is Praetorian Guard.

**Comment by Natherul** [comment]
Fix pending

**Comment by sioding** [comment]
fixed with patch from 16.2.2019

**Comment by Simtexx** [comment]
Bug is back
![Desktop Screenshot 2019 08 13 - 19 11 40 62](https://user-images.githubusercontent.com/18119601/62962411-2a918200-bdff-11e9-8b28-0e6b1a828dce.png)

**Comment by Natherul** [comment]
not same bug, and also a fix is pending for this. When adding proper check last week I forgot that guild leaders are not alliance officers but alliance leaders and as such they lack the right to invite to alliance atm
