### ISSUE TITLE
[Quest] Corruption of Desire

### ISSUE THREAD

**Issue by lakeyours** [WarEmu/WarBugs#5416]
Quest: Desire of Corruption.
Faction: Order.
Location: Order T2 Warcamp / Troll Country.
Quest Giver: Friedrich Haelund.
Bug Reporter: Gentleman (Account Lakeyours)
Error: 
1. The quest location on the map is incorrect. It now shows the PQ "Grave Diggers" when it should show "Crypt of Weapons" in the T2 RVR Battlefield.
2. You can't interact with "Tainted Earth". Once you find it you can't click on it and therefore not being able to complete the quest.
Solution: 
1. Show quest location "Crypt of Weapons" on map.
2. Make "Tainted Earth" interactable and make it complete quest conditions.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by LadyCereus** [comment]
Still doesn't seem to be working.  Map correction is working - it now highlights the correct spot for the Tainted Earth.  You can interact with the Tainted Earth and get credit for clicking it, but then it's a dead end.  Quest log says to return to Hogar Putnam (in the Tier 2 war camp) but he won't talk.

**Comment by NorKalli** [comment]
entire quest confirmed working
