### ISSUE TITLE
Quest: Head of the Viper   Cannot finish quest

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6717]
I got to the point in the quest line where it asks me to kill Loridian Nynx in the Temple.  You are supposed to get past the barrier and be able to enter and kill her, but the barrier is impenetrable. There is no other way into the building.  You cannot aggro her, or get an axe to her to get her outside either.

![xramoth_010](https://cloud.githubusercontent.com/assets/15041016/15875127/1988713e-2ccc-11e6-8305-bf7fe29f952c.jpg)

**Comment by szejoza** [comment]
Same quest, different stage - can't progress further as NPCs to rescue are not in the marked area or close vicinity
![sheykis_022](https://user-images.githubusercontent.com/18032193/39012713-7c978c26-4415-11e8-8a70-3625f4fe4064.jpg)

**Comment by Sinrman** [comment]
Just to update. This quest is still broken.  There is an impenetrable force field that won't allow you to pass. You can target the required Mob but you can't see them or hit them to gain aggro. 
![gunnr_013](https://user-images.githubusercontent.com/42098334/47045579-c65b4e80-d158-11e8-9dd7-393fbfc1244e.jpg)
![gunnr_015](https://user-images.githubusercontent.com/42098334/47045603-d5420100-d158-11e8-84af-f4587b5447a5.jpg)
![gunnr_014](https://user-images.githubusercontent.com/42098334/47045615-dd01a580-d158-11e8-99f6-df24f5623a31.jpg)

**Comment by sioding** [comment]
fixed with patch from 05.11.2018

**Comment by DyseMcLay** [comment]
There still seems to be a problem getting through the shield, still can't complete this quest even after "killing" it.
![Chofer_003](https://user-images.githubusercontent.com/52871378/61369827-927f9780-a856-11e9-9e93-43df976f2d4f.jpg)

**Comment by Lheana** [comment]
There is an orb right behind you, called 'Portal'. Try it.

**Comment by DyseMcLay** [comment]
Sure enough, I'm blind lol
