### ISSUE TITLE
Murgluk's Gits Public Quest - PQ Dwarf Chapter 2

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7174]
This one is messy and tricky.
- [x] Dusty bags and Pile of Coal in first stage are standing outside of the PQ area id so there is no cursor to interact with them.As long as you get close to the elevator the PQ UI/Counter will show up and then you can interact normally with bags and Pile next to the elevator.
- [x] According to the above problem PQ area ID needs enlargement.PQ UI needs to show up when you enter the cave.
**P.s Other then that PQ is working fine in all stages!**

**Comment by wargrimnir** [comment]
Should be fixed.

**Comment by Soulwhisper** [comment]
@wargrimnir I dont know if its patched or not but its still buggy. 
And it acts really weird! I will post a video later on. Just tell me if you patched it.

**Comment by Razielhell** [comment]
https://www.youtube.com/watch?v=S_wh5dkIqcA
Check how weird it bahaves.

**Comment by wargrimnir** [comment]
I don't think this is fixable, the PQ wasn't fully loaded. I've noticed this on the dev server. Sometimes it can take up to a minute or so for everything to pop in. Usually not as big a deal on live as they stay active for a while if people are in the zone.

**Comment by Razielhell** [comment]
Pay attention to 0:27 - 0:28 . I dont know what is that but it triggers in specific areas inside of any PQ. 
You noticed that at 0:27 when it triggered i could normally click on Coal and Bags right? :P

**Comment by Luth-RoR** [comment]
I think you have the same effect when you reach the altdorf marketplace. There is a short lag as the server side objects are loaded into the client (my guess). It seems that there are triggers around, as it happens always at the same spots/borders. I also guess that these triggers are placed in the client.

**Comment by Razielhell** [comment]
Yeah as i said these triggers need to be placed once you enter the "barrier" of a PQ area and of course when the PQ Stages change.

**Comment by Lheana** [comment]
PQ area is fine now.
