### ISSUE TITLE
Laurilion Caves PQ - High Elf Chapter 6 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7222]
- [x] PQ area ID must be increased into Major Landmark Laurilion's Caverns ( There are plenty of PQ mobs in there).It counts them and rewards you influence if you kill them but UI/Counter doesnt show up.
- [x] Also very few Reavers and too many Brigands for stage 1.Needs more Reavers.

**Comment by wargrimnir** [comment]
Fixed map area. Added more Reavers.

**Comment by Soulwhisper** [comment]
- PQ tracker still doesnt show when you move towards cave.Here is the dead-line.
![warhammer online age of reckoning 12 24 2016 - 18 34 52 83](https://cloud.githubusercontent.com/assets/16864486/21467949/ba0231d0-ca07-11e6-822e-faf1eec337b9.png)

**Comment by Soulwhisper** [comment]
Fixed o.O
