### ISSUE TITLE
High Elf Chapter 5-6 Area ID (Influence/Chapter Bar)

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7226]
- Entering the PQ Cold-Hearted Predators doesnt change to Chapter 5.First picture shows chapters as they are now(Bugged).Second one as they should.
**In other words Chapter 5 must cover the Cold-Hearted Predators PQ.**
  ![bugged](https://cloud.githubusercontent.com/assets/16864486/17638482/e5ff3220-60f2-11e6-98be-396a2d8c0b20.jpg)
  ![fixed](https://cloud.githubusercontent.com/assets/16864486/17638483/e82a7064-60f2-11e6-81e6-c42d0ff9f570.jpg)

**Comment by wargrimnir** [comment]
Fixed in next.

**Comment by Soulwhisper** [comment]
- [ ] This isnt fixed.Still the same issue.In PQ Cold-Hearted Predators still shows Chapter 6.

**Comment by wargrimnir** [comment]
It does, you just had the other PQ in the way. The range extends into part of the camp now.

**Comment by Soulwhisper** [comment]
@wargrimnir Hmm?? It should be like this.Uploading video in a sec.
![142143](https://cloud.githubusercontent.com/assets/16864486/21470446/965361a6-ca92-11e6-9d55-253bba077358.png)

**Comment by wargrimnir** [comment]
Don't. I replied to the wrong ticket. Maybe the areas map didn't get pushed then. All of that cave on the right side should be ch5 as well.
