### ISSUE TITLE
Steinbruck Manor - Public Quest Destruction Chaos Chapter 10 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7365]
- [x] Stage 1 kinda half works.PQ UI is bugged with farmhands at X/50.000 although you can farm the farmhands...it counts them and give you influence.
- [x] Killing Watch though doesnt reward neither tracks the kills.

**Comment by wargrimnir** [comment]
Fixed the Farmhands counter, I think it's 10 kills now.

**Comment by Razielhell** [comment]
@Luth-RoR Killing Steinbruck Watch still doesnt count them so you cant get past Stage 1.

**Comment by Luth-RoR** [comment]
kk

**Comment by Lheana** [comment]
Has been fixed
