### ISSUE TITLE
Assault on Coal Ridge Depot - Public Quest Dwarf Chapter 6

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8291]
Hargrim

Order:
- Assault on Coal Ridge Depot in Marshes of Madness is fully operational.

- [x] Not working.There are no mobs in the area.I managed to find only 1 Black skull warrior under/inside a tree and he didnt give me influ nor counted on the tracker.

**_P.s Unless you have to do something else in Stage 1 or im that blind._**

**Comment by Soulwhisper** [comment]
@Luth-RoR how is it possible that i added labels here? :P

**Comment by Luth-RoR** [comment]
Probably a bug in github; i actually added them.

**Comment by Soulwhisper** [comment]
@Luth-RoR Should i make a report it? xD

**Comment by Luth-RoR** [comment]
Something like that happened in the past iirc, when they messed up the fonts on the side.

**Comment by Soulwhisper** [comment]
LMAO.Fixed.Dont know who or how but mobs appear now.

**Comment by Soulwhisper** [comment]
LOL re-opening.
- [ ] Stage 2 doesnt work.Cant interact with boxes(Signal flares)

**Comment by wargrimnir** [comment]
Hm, I checked this one last week. It was working.

**Comment by Soulwhisper** [comment]
Gonna check it again now.

**Comment by Soulwhisper** [comment]
Nope.They dont work :( Clicking on them does nothing.

**Comment by Soulwhisper** [comment]
Objectives needs signal flares.Signal flares(Check picture)dont work clicking on them.Clicking on Signal Fire objects though works.
![warhammer online age of reckoning 12 21 2016 - 19 37 31 04](https://cloud.githubusercontent.com/assets/16864486/21399671/2b1bea6e-c7b5-11e6-9735-4d28bf03ad61.png)

**Comment by Soulwhisper** [comment]
If i needed to guess...you should click on Signal flares(Get items in your backpack) then go to Signal Fire and fire up each one individually?

**Comment by wargrimnir** [comment]
I see, the stage objective just needs to be changed to Signal Fire.

This is the current Stage 2 description
> The Black Skull greenskins have been beaten back for the moment. Light the Signal fires to let the gyrocopter pilots know it's safe to land!

Fixed objective name in next patch.

**Comment by thorbolt80** [comment]
Trying today still not working. You can't act in stage 2 with signal flare
