### ISSUE TITLE
Entering SC from T1 zone causes chicken state

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#856]
Enter sc from t1 zone make you transform  into chicken

- log out and relog do not make you return in sc(as it was until now), it make you return to your previusly zone,  but if you flag, you get sc score menu and also  when sc end you return to your original location

- and due being flag and signed as combat in t1   you beacame chicken

- also if you were mounted you became on mount but chicken. (Chicken status should remove all buff from you indeed)

I described all just in case, but after fix chicken this should not create other issues.

**Comment by ozarmidrashim** [comment]
Was fixed a while back

**Comment by Tiggonos** [comment]
still an issue. when you are NOT a chicken and enter sc from t1 it makes you a chicken in the sc. (when entering as chicken it dechickens you).

as you need to go to t1 vendor for crafting supplies (any other vendor dont have any) this is an issue.
