### ISSUE TITLE
The Defiled Anvil - Public Quest Dwarf Chapter 22

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8921]
- [X] Stage 1 bugged.

**Comment by Luth-RoR** [comment]
Doesn't work at all?

**Comment by Soulwhisper** [comment]
Stage 2 ? Yes. Needs to click on objects (Rocks iirc) but non of them are targetable/clickable.

**Comment by Natherul** [comment]
should be fixed with the next patch, also saved the poor poor nurgle beast from a fate far worse then death (death will be fine for this creature)

**Comment by Razielhell** [comment]
- [ ] Still cant click on the Stones...
![warhammer online age of reckoning 01 25 2017 - 12 40 05 01](https://cloud.githubusercontent.com/assets/16864486/22287451/ad16fc8c-e2fb-11e6-8a62-3a3d34396db6.png)
![warhammer online age of reckoning 01 25 2017 - 12 40 12 02](https://cloud.githubusercontent.com/assets/16864486/22287452/ad1932c2-e2fb-11e6-8ac9-95446518ae2c.png)

**Comment by Thayli** [comment]
Seems to work fine on dev? Not sure what's going on here.

**Comment by Razielhell** [comment]
Yeah...nobody knows yet.

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by thorbolt80** [comment]
The five stone are not targetable anymore.

**Comment by Razielhell** [comment]
?? Works fine.

**Comment by Razielhell** [comment]
Made the rocks on Stage II destroyable.
