### ISSUE TITLE
"Nobility" quest for Order in Troll Country

### ISSUE THREAD

**Issue by banned85** [WarEmu/WarBugs#9465]
after killing 10 Blighted Ghouls (thats all what u must to do in this quest) i speak with quest giver-priestess serilda then click "Complete" and nothing happens, i dont get any rewards or money, quest is still active and she has still this orange "ring" over her head

**Comment by wargrimnir** [comment]
Maybe fixed in next. These were set to RvR quests instead of standard quests.

**Comment by LadyCereus** [comment]
Just to update as of 5/20/17 Nobility still can't be completed.

**Comment by Ryanfawkez** [comment]
Destruction item rewards on an Order quest = buggy hand-ins.

**Comment by Ryanfawkez** [comment]
Fixed rewards and slapped them onto the second quest.
