### ISSUE TITLE
Missing NPC

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#9926]
Hi, i got 3 quest and need finish in Marshes of Madness Dwrf WC, Hagar Ironrune but npc missing. im not find in WC and i dont know but maybe when cant finish this quest, cant pick up chasing oathgold epick helm quest.

Thx for answer

**Comment by Razielhell** [comment]
quest name please

**Comment by Dragothurch** [comment]
3 quest: Reinforcement, Know the enemy,Trouble in the marshes

**Comment by Razielhell** [comment]
Fixed the NPC that was missing. 
The epic quest for the helm starts at Dwarf Chapter 5, from NPC  Dainna Fornbili.

**Comment by Dragothurch** [comment]
Hagar Ironrune not here in WC, not fixed(epic helm quest my mistake)

**Comment by Razielhell** [comment]
Will be fixed next Patch.

**Comment by Dragothurch** [comment]
thx
